import path from "node:path";
import { spawnSync } from "node:child_process";
import { ROOT_DIR } from "./config.mjs";

const FALLBACK_PLAN = {
  moduleName: "moonap_generated/runtime",
  entryPackage: "cmd/main",
  target: "wasm",
  buildArgs: ["build", "cmd/main", "--target", "wasm"],
  wasmOutputPath: "_build/wasm/debug/build/cmd/main/main.wasm",
  templateFiles: [
    {
      path: "moon.mod.json",
      content: JSON.stringify(
        {
          name: "moonap_generated/runtime",
          version: "0.1.0",
          readme: "README.md",
          repository: "",
          license: "Apache-2.0",
          keywords: ["moonap", "wasm", "moonbit"],
          description: "Generated by MoonAP",
        },
        null,
        2,
      ),
    },
    { path: "moon.pkg", content: "// Generated by MoonAP\n" },
    { path: "README.md", content: "# Generated by MoonAP\n" },
  ],
  packageFileContent: `options(
  "is-main": true,
)`,
  packageFileWithExportsTemplate: `options(
  "is-main": true,
  link: {
    "wasm": {
      "exports": [
__MOONAP_WASM_EXPORTS__
      ]
    }
  }
)`,
  generatedPackageFileContent: "// Generated by MoonAP\n",
  packageDirsExcludedFromAutofill: ["cmd/main"],
};

function templateFileFromMoonBit(file) {
  return {
    path: String(file?.path || "").trim(),
    content: String(file?.content || ""),
  };
}

function planFromMoonBit(plan) {
  return {
    moduleName: String(plan?.module_name || FALLBACK_PLAN.moduleName).trim(),
    entryPackage: String(plan?.entry_package || FALLBACK_PLAN.entryPackage).trim(),
    target: String(plan?.target || FALLBACK_PLAN.target).trim(),
    buildArgs: Array.isArray(plan?.build_args) ? plan.build_args.map(String).filter(Boolean) : FALLBACK_PLAN.buildArgs,
    wasmOutputPath: String(plan?.wasm_output_path || FALLBACK_PLAN.wasmOutputPath).trim(),
    templateFiles: Array.isArray(plan?.template_files)
      ? plan.template_files.map(templateFileFromMoonBit).filter((file) => file.path)
      : FALLBACK_PLAN.templateFiles,
    packageFileContent: String(plan?.package_file_content || FALLBACK_PLAN.packageFileContent),
    packageFileWithExportsTemplate: String(plan?.package_file_with_exports_template || FALLBACK_PLAN.packageFileWithExportsTemplate),
    generatedPackageFileContent: String(plan?.generated_package_file_content || FALLBACK_PLAN.generatedPackageFileContent),
    packageDirsExcludedFromAutofill: Array.isArray(plan?.package_dirs_excluded_from_autofill)
      ? plan.package_dirs_excluded_from_autofill.map(String).filter(Boolean)
      : FALLBACK_PLAN.packageDirsExcludedFromAutofill,
  };
}

function loadMoonBitCompilerPlan() {
  const moonapDir = path.join(ROOT_DIR, "moonap");
  const result = spawnSync("moon", ["run", "cmd/compiler_plan"], {
    cwd: moonapDir,
    encoding: "utf8",
    timeout: 5000,
    windowsHide: true,
  });
  if (result.status !== 0 || !String(result.stdout || "").trim()) {
    return null;
  }
  return planFromMoonBit(JSON.parse(String(result.stdout).trim()));
}

const COMPILER_PLAN = loadMoonBitCompilerPlan() || FALLBACK_PLAN;

export function getCompilerPlan() {
  return COMPILER_PLAN;
}

export function renderMainPackageFile(exportsList = []) {
  const cleanExports = exportsList.filter((name) => typeof name === "string" && name.trim().length > 0);
  if (cleanExports.length === 0) {
    return COMPILER_PLAN.packageFileContent;
  }
  const exportLines = cleanExports.map((name) => `          "${name}"`).join(",\n");
  return COMPILER_PLAN.packageFileWithExportsTemplate.replace("__MOONAP_WASM_EXPORTS__", exportLines);
}
